# Write your MySQL query statement below
SELECT DISTINCT S.NAME FROM SalesPerson S WHERE S.SALES_ID NOT IN(
    SELECT SALES_ID FROM ORDERS WHERE ORDERS.COM_ID = (
        SELECT COM_ID FROM COMPANY WHERE NAME = 'RED'
    )
)